"""empty message

Revision ID: 20fdd72a7e81
Revises: 43a660ce8bde
Create Date: 2015-04-12 19:38:44.593822

"""

# revision identifiers, used by Alembic.
revision = '20fdd72a7e81'
down_revision = '43a660ce8bde'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_slug'), 'post', ['slug'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_slug'), table_name='post')
    ### end Alembic commands ###
