"""empty message

Revision ID: 3a0b1481f0fd
Revises: 4e51a72fe63c
Create Date: 2015-04-26 10:33:44.956303

"""

# revision identifiers, used by Alembic.
revision = '3a0b1481f0fd'
down_revision = '4e51a72fe63c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PostTag',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PostTag')
    ### end Alembic commands ###
