"""empty message

Revision ID: 4e51a72fe63c
Revises: 555d01aff0a9
Create Date: 2015-04-26 10:31:33.092536

"""

# revision identifiers, used by Alembic.
revision = '4e51a72fe63c'
down_revision = '555d01aff0a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    ### end Alembic commands ###
