"""empty message

Revision ID: 5068f9657fcb
Revises: 3a0b1481f0fd
Create Date: 2015-04-26 17:37:44.201032

"""

# revision identifiers, used by Alembic.
revision = '5068f9657fcb'
down_revision = '3a0b1481f0fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tag',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.drop_table('PostTag')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PostTag',
    sa.Column('tag_id', sa.INTEGER(), nullable=True),
    sa.Column('post_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], [u'post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], [u'tag.id'], )
    )
    op.drop_table('post_tag')
    ### end Alembic commands ###
