"""empty message

Revision ID: 555d01aff0a9
Revises: 20fdd72a7e81
Create Date: 2015-04-12 21:16:20.005388

"""

# revision identifiers, used by Alembic.
revision = '555d01aff0a9'
down_revision = '20fdd72a7e81'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
